version: '2'
services:
  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/volume-sfo2-01/cj:/mnt/volume-sfo2-01/cj
    depends_on:
      - phpapache
    restart: always
  phpapache:
    build: ../phpapache
    expose:
      - "80"
    volumes:
      - /mnt/volume-sfo2-01/cj/carltonjosephdotcom:/var/www/html
    restart: always
  tinaandcarlton2weddinginvite:
    build: /mnt/volume-sfo2-01/cj/tinaandcarltondotcom/weddinginvite
    environment:
      PORT: 5000
    restart: always
  tinaandcarlton3wedding:
    build: /mnt/volume-sfo2-01/cj/tinaandcarltondotcom/wedding
    environment:
      PORT: 5000
    restart: always

