version: '2'
services:
  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/volume-sfo2-01/cj:/mnt/volume-sfo2-01/cj
#    depends_on:
#      - phpapache
    restart: always
#  phpapache:
#    build: ../phpapache
#    expose:
#      - "80"
#    volumes:
#      - /mnt/volume-sfo2-01/cj/carltonjosephdotcom:/var/www/html
#    restart: always
  tinaandcarlton2weddinginvite:
    build: ../tinaandcarltondotcom/weddinginvite
    environment:
      PORT: 5000
    volumes:
      - /mnt/volume-sfo2-01/cj/tinaandcarltondotcom/weddinginvite:/usr/src/app
    restart: always
  tinaandcarlton3wedding:
    build: ../tinaandcarltondotcom/wedding
    environment:
      PORT: 5000
    volumes:
      - /mnt/volume-sfo2-01/cj/tinaandcarltondotcom/wedding:/usr/src/app
    restart: always
  tinaandcarlton4honeymoon:
    build: ../tinaandcarltondotcom/honeymoon
    environment:
      PORT: 5000
    volumes:
      - /mnt/volume-sfo2-01/cj/tinaandcarltondotcom/honeymoon:/usr/src/app
    restart: always
  apps4tracking:
    build: ../apps4tracking/server
    environment:
      PORT: 5000
    volumes:
      - /mnt/volume-sfo2-01/cj/apps4trackingdotcom:/usr/src/app
    restart: always

